services:

  webapp:
    image: ghcr.io/ecolink-webapp-build:${OCELOT_VERSION:-latest}
    build:
      target: build
      context: .

  backend:
    image: ghcr.io/ecolink-backend-build:${OCELOT_VERSION:-latest}
    build:
      target: build
      context: backend

  maintenance:
    image: ghcr.io/ecolink-maintenance-build:${OCELOT_VERSION:-latest}
    build:
      target: build
      context: .
      dockerfile: ./Dockerfile.maintenance
