services:

  webapp:
    image: ghcr.io/ecolink-webapp-base:${OCELOT_VERSION:-latest}
    build:
      target: base
      context: webapp

  backend:
    image: ghcr.io/ecolink-backend-base:${OCELOT_VERSION:-latest}
    build:
      target: base
      context: backend

  maintenance:
    image: ghcr.io/ecolink-maintenance-base:${OCELOT_VERSION:-latest}
    build:
      target: base
      context: webapp
      dockerfile: ./Dockerfile.maintenance
