# input _RoomFilter {
#   AND: [_RoomFilter!]
#   OR: [_RoomFilter!]
#   id: ID
#   users_some: _UserFilter
# }

# TODO change this to last message date
enum _RoomOrdering {
  lastMessageAt_desc
  createdAt_desc
}

type Room {
  id: ID!
  createdAt: String
  updatedAt: String

  users: [User]! @relation(name: "CHATS_IN", direction: "IN")

  roomId: String! @cypher(statement: "RETURN this.id")
  isGroup: Boolean! @cypher(statement: """
    MATCH (this)<-[:CHATS_IN]-(user:User)
    WITH count(user) as userCount, this.isGroup as explicitGroup
    RETURN COALESCE(explicitGroup, userCount > 2)
  """)
  groupName: String @cypher(statement: "RETURN this.groupName")
  groupAvatar: String @cypher(statement: """
    OPTIONAL MATCH (this)-[:GROUP_AVATAR]->(image:Image)
    RETURN image.url
  """)
  roomName: String! @cypher(statement: """
    MATCH (this)<-[:CHATS_IN]-(user:User)
    WITH count(user) as userCount, this
    WITH CASE 
      WHEN userCount > 2 AND this.groupName IS NOT NULL THEN this.groupName
      WHEN userCount > 2 THEN 'Group Chat'
      ELSE [(this)<-[:CHATS_IN]-(u:User) WHERE NOT u.id = $cypherParams.currentUserId | u.name][0]
    END AS name
    RETURN name
  """)
  avatar: String @cypher(statement: """
    MATCH (this)<-[:CHATS_IN]-(user:User)
    WITH count(user) as userCount, this
    WITH CASE 
      WHEN userCount > 2 THEN [(this)-[:GROUP_AVATAR]->(img:Image) | img.url][0]
      ELSE [(this)<-[:CHATS_IN]-(u:User) WHERE NOT u.id = $cypherParams.currentUserId | [(u)-[:AVATAR_IMAGE]->(img:Image) | img.url]][0][0]
    END AS avatarUrl
    RETURN avatarUrl
  """)

  lastMessageAt: String

  lastMessage: Message @cypher(statement: """
    MATCH (this)<-[:INSIDE]-(message:Message)
    WITH message ORDER BY message.indexId DESC LIMIT 1
    RETURN message
  """)

  unreadCount: Int @cypher(statement: """
    MATCH (this)<-[:INSIDE]-(message:Message)<-[:CREATED]-(user:User)
    WHERE NOT user.id = $cypherParams.currentUserId
      AND NOT message.seen 
    RETURN count(message)
  """)
}

type Mutation {
  CreateRoom(
    userId: ID
    userIds: [ID!]
    groupName: String
  ): Room
  AddUsersToRoom(
    roomId: ID!
    userIds: [ID!]!
  ): Room
  RemoveUserFromRoom(
    roomId: ID!
    userId: ID!
  ): Room
  UpdateRoomName(
    roomId: ID!
    groupName: String!
  ): Room
  LeaveRoom(
    roomId: ID!
  ): Boolean
  DeleteRoom(
    roomId: ID!
  ): Boolean
}

type Query {
  Room(
    id: ID
    orderBy: [_RoomOrdering]
  ): [Room]
  UnreadRooms: Int
}

type Subscription {
  roomCountUpdated: Int
}
